spring:
  application:
    name: app2
  cloud:
      consul:
        discovery:
          enabled: true
          tags: version=1.2,name=springcloudtest
          health-check-path: /health-check
          health-check-interval: 5s
          instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
          prefer-ip-address: true
        host: 192.168.199.231
        port: 8500

server:
  port: 7202

