spring:
  application:
    name: app1
  cloud:
    consul:
      discovery:
        enabled: true
        health-check-path: /health-check
        health-check-interval: 30s
        tags: version=1.2,name=springcloudtest
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        prefer-ip-address: true
      host: 192.168.199.231
      port: 8500


server:
  port: 7201