spring:
  application:
    name: gw-zuul
  cloud:
    zookeeper:
      discovery:
        root: /spring-cloud-services
      connect-string: localhost:2181


server:
  port: 7301

zuul:
  prefix: /gw
  routes:
    app1 :
      path: /app1/**
      serviceId: app1
    app2:
      path: /app2/**
      serviceId: APP2
    app3:
      path: /app3/**
      serviceId: app3
  strip-prefix: true



